apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: continuous-deployment
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update", "list",'patch']
