apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-po
      labels:
        app: my-app
    spec:
      containers:
        - name: getting-started
          image: abhijithababhijith/getting-started-expressjs
          resources:
            limits:
                cpu: '100m'
                memory: '128Mi'
          ports:
            - containerPort: 3000





---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
     app: my-app
  ports:
    - port: 3000
      targetPort: 3000