apiVersion: v1
current-context: {context-name}
kind: Config
clusters:
- cluster:
    certificate-authority-data: {cluster-ca}
    server: {server-dns}
  name: {cluster-name}
contexts:
- context:
    cluster: {cluster-name}
    user: {user-name}
  name: {context-name}

users:
- name: {user-name}
  user:
    token: {secret-token}