name: Build And Deploy k8s

on:
  push:
    branches:
      - "main"
env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_BASE64 }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Logs
        uses: ghostzero/kubectl@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_BASE64 }}
        with:
          args: get pods
      # - name: Install kubectl
      #   run: |
      #      curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      #      chmod +x ./kubectl
      #      kubectl version --output=yaml

