name: Build And Deploy k8s

on:
  push:
    branches:
      - "main"
env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_BASE64 }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Deployment
        uses: cube-root/kubectl@1.0.1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_BASE64 }}
        with:
          # command: kubectl set image deployment/sample-express getting-started=abhijithababhijith/getting-started-expressjs:latest
          command: kubectl get pods
       